language: go
go:
    - 1.1
notifications:
    irc:
        channels:
            - "irc.mozilla.org#heka"
before_install:
    - sudo apt-get install libprotobuf-c0-dev libprotobuf7 cmake

install:
    - . build.sh

script:
    - make test
